
# site
url: http://ng2.site
safe: true

# Blog settings
# permalink: /blog/:title

paginate: 20
paginate_path: "/page:num/"

# My variables
name: Monkey92
description: 好好学习,天天向上
google_verification: null
author: Monkey92
github: monkey92
cnzz: true


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]


# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
markdown: kramdown
kramdown:
  input: GFM
  #hard_wrap: false
highlighter: rouge
highlight: true

gems: [jekyll-paginate]